version: '2'
services:
  nodered:
    build: .
    environment:
     - VIRTUAL_HOST=nodered.example.com
     - VIRTUAL_PORT=1880
    ports:
     - "1880:1880"
    expose:
     - "1880"
    restart: always
    volumes:
     - "/usr/local/lib/node_modules/"
